services:
  products-db:
    image: postgres:16-alpine
    container_name: marketplace-products-db
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - products-db-data:/var/lib/postgresql/data

volumes:
  products-db-data:
